backend:
  name: github
  repo: abdulazizkhasanboyevich/my-blog
  branch: main
  base_url: https://poetic-vacherin-b7367e.netlify.app

media_folder: images
public_folder: images

collections:
  - name: posts
    label: Blog Postlar
    folder: _posts
    create: true
    fields:
      - { label: Sarlavha, name: title, widget: string }
      - { label: Sana, name: date, widget: datetime }
      - { label: Kategoriya, name: category, widget: string }
      - { label: Qisqa tavsif, name: excerpt, widget: text }
      - { label: Rasm, name: image, widget: image }
      - { label: Matn, name: body, widget: markdown }

backend:
  name: github
  repo: abdulazizkhasanboyevich/my-blog
  branch: main
  base_url: https://poetic-vacherin-b7367e.netlify.app